name: Frontend CI

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'frontend/**'

jobs:
  customer-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/customer-app/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend/customer-app
        npm ci
    
    - name: Lint
      run: |
        cd frontend/customer-app
        npm run lint
    
    - name: Build
      run: |
        cd frontend/customer-app
        npm run build
  
  vendor-app:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/vendor-app/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend/vendor-app
        npm ci
    
    - name: Lint
      run: |
        cd frontend/vendor-app
        npm run lint
    
    - name: Build
      run: |
        cd frontend/vendor-app
        npm run build
  
  admin-panel:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/admin-panel/package-lock.json
    
    - name: Install dependencies
      run: |
        cd frontend/admin-panel
        npm ci
    
    - name: Lint
      run: |
        cd frontend/admin-panel
        npm run lint
    
    - name: Build
      run: |
        cd frontend/admin-panel
        npm run build
